/* Reproducible browser acceptance check. Set PLAYWRIGHT_MODULE to a bundled
 * playwright module directory, or install playwright locally to use this file. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

(async () => {
  const capture = !process.argv.includes('--no-capture');
  const executablePath = process.env.CHROMIUM_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
  const browser = await chromium.launch({ headless: true, executablePath });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const base = process.env.SANAD_URL || 'http://127.0.0.1:4173/';
  const errors = [];
  const externalRequests = [];
  context.on('page', p => p.on('pageerror', e => errors.push(e.message)));
  page.on('pageerror', e => errors.push(e.message));
  context.on('request', r => { if (!r.url().startsWith(new URL(base).origin) && !r.url().startsWith('blob:')) externalRequests.push(r.url()); });
  await fs.mkdir('.impeccable/review', { recursive: true });
  await fs.mkdir('test-results', { recursive: true });
  try {
    await page.goto(base);
    await page.getByRole('button', { name: 'Review payment options', exact: false }).waitFor();
    assert.equal(await page.locator('.decision-sheet').count(), 0);
    await page.getByRole('button', { name: 'Finance', exact: true }).click();
    assert.equal(await page.locator('.conversation').count(), 0);
    await page.getByRole('heading', { name: 'How should this invoice be paid?' }).waitFor();
    await page.evaluate(() => document.fonts.ready);
    if (capture) await page.screenshot({ path: '.impeccable/review/desktop.png', fullPage: true });
    assert.match(await page.locator('.receipt-callout').innerText(), /5,965/);
    await page.getByRole('radio', { name: /Specialist transfer/ }).click();
    await page.getByLabel('Who covers downstream fees?').selectOption('buyer');
    await page.locator('.cost-breakdown summary').click();
    assert.match(await page.locator('.breakdown-total').innerText(), /9,080\.12/);
    assert.match(await page.locator('.savings-note').innerText(), /242\.75/);
    await page.locator('.stress-panel summary').click();
    await page.getByLabel('Change in CAD cost per euro').fill('5');
    assert.equal(await page.locator('.slider-label output').innerText(), '+5%');
    assert.match(await page.locator('.scenario-result').innerText(), /9,533\.73/);
    await page.getByRole('button', { name: 'Chat', exact: true }).click();
    await page.getByLabel('Message as Bilal Mansouri').fill('I will cover the estimated downstream fees.');
    await page.getByRole('button', { name: 'Send message', exact: true }).click();
    assert.match(await page.locator('.chat-timeline').innerText(), /I will cover/);
    await page.getByRole('button', { name: 'Finance', exact: true }).click();
    await page.getByRole('button', { name: 'Review agreement', exact: true }).click();
    await page.getByRole('heading', { name: 'A clear agreement, for both of you.' }).waitFor();
    const firstHash = await page.locator('.hash-strip code').innerText();
    assert.equal(firstHash.length, 64);
    const signButton = page.getByRole('button', { name: 'Sign as Bilal', exact: true });
    assert.equal(await signButton.isDisabled(), true);
    await page.getByRole('checkbox').check();
    await signButton.click();
    await page.getByRole('button', { name: 'Review as Amira' }).waitFor();
    assert.equal(await page.locator('.signature-slot.signed').count(), 1);

    // The second party joins after the first signature, in the same browser.
    const otherPagePromise = context.waitForEvent('page');
    await page.getByRole('button', { name: 'Open other party in a tab' }).click();
    const other = await otherPagePromise;
    await other.waitForLoadState();
    await other.getByRole('button', { name: 'Sign as Amira', exact: true }).waitFor();
    assert.equal(await other.locator('.hash-strip code').innerText(), firstHash);
    await other.getByRole('checkbox').check();
    await other.getByRole('button', { name: 'Sign as Amira', exact: true }).click();
    await other.getByRole('heading', { name: 'Agreed. And worth keeping.' }).waitFor();
    await page.getByRole('heading', { name: 'Agreed. And worth keeping.' }).waitFor();
    assert.equal(await page.locator('.signature-slot.signed').count(), 2);
    assert.equal(await page.locator('.hash-strip code').innerText(), firstHash);
    await page.evaluate(() => window.scrollTo(0, 0));
    if (capture) await page.screenshot({ path: '.impeccable/review/sealed.png', fullPage: true });
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download signed record', exact: true }).click();
    const download = await downloadPromise;
    const recordPath = path.resolve('test-results', download.suggestedFilename());
    await download.saveAs(recordPath);
    const exported = JSON.parse(await fs.readFile(recordPath, 'utf8'));
    assert.equal(exported.signatures.length, 2);
    assert.equal(exported.snapshot.quote.id, 'specialist-transfer');
    assert.equal(exported.snapshot.costs.totalMaxCad, 9080.12); // Stress is not a forecast/locked quote.
    assert.ok(exported.signatures.every(s => !('d' in s.publicKeyJwk)));
    await page.getByRole('button', { name: 'Verify or test a change' }).click();
    await page.getByLabel('Upload signed record').setInputFiles(recordPath);
    await page.getByRole('heading', { name: 'Record intact. Both signatures valid.' }).waitFor();
    await page.getByRole('button', { name: 'Test a changed amount' }).click();
    await page.getByRole('heading', { name: 'This record did not pass verification.' }).waitFor();
    if (capture) await page.screenshot({ path: '.impeccable/review/verification.png', fullPage: true });
    await page.getByRole('button', { name: 'Check original' }).click();
    await page.getByRole('heading', { name: 'Record intact. Both signatures valid.' }).waitFor();
    await page.getByRole('button', { name: 'Close dialog' }).click();
    await page.getByRole('button', { name: 'Revise terms', exact: true }).click();
    await page.getByRole('button', { name: 'Start new draft', exact: true }).click();
    await page.getByRole('heading', { name: 'How should this invoice be paid?' }).waitFor();
    await other.getByRole('heading', { name: 'How should this invoice be paid?' }).waitFor();
    await other.close();
    await page.getByRole('button', { name: 'Edit invoice', exact: true }).click();
    await page.getByLabel('Quantity · bottles').fill('1');
    await page.getByRole('button', { name: 'Update invoice' }).click();
    assert.match(await page.getByRole('alert').innerText(), /at least/);
    await page.getByLabel('Quantity · bottles').fill('240');
    await page.getByRole('button', { name: 'Update invoice' }).click();
    assert.match(await page.locator('.sheet-heading').innerText(), /3,000/);
    await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Reset demo', exact: true }).click();
    assert.match(await page.locator('.sheet-heading').innerText(), /6,000/);
    await page.getByRole('button', { name: 'Chat', exact: true }).click();
    assert.equal(await page.locator('.message-group').count(), 3);
    await page.getByRole('button', { name: 'Finance', exact: true }).click();
    // Same-tab role switching path, including consent reset.
    await page.getByRole('button', { name: 'Review agreement', exact: true }).click();
    await page.getByRole('checkbox').check();
    await page.getByRole('button', { name: 'Sign as Bilal', exact: true }).click();
    await page.getByRole('button', { name: 'Review as Amira' }).click();
    assert.equal(await page.getByRole('checkbox').isChecked(), false);
    await page.getByRole('checkbox').check();
    await page.getByRole('button', { name: 'Sign as Amira', exact: true }).click();
    await page.getByRole('heading', { name: 'Agreed. And worth keeping.' }).waitFor();
    // Fresh mobile session, full signing path, keyboard native controls.
    const mobile = await context.newPage();
    await mobile.setViewportSize({ width: 390, height: 844 });
    await mobile.goto(base);
    await mobile.getByRole('heading', { name: 'Amira Ben Youssef' }).waitFor();
    await mobile.evaluate(() => document.fonts.ready);
    if (capture) await mobile.screenshot({ path: '.impeccable/review/mobile-chat.png', fullPage: true });
    assert.equal(await mobile.locator('.decision-sheet').count(), 0);
    const composer = await mobile.locator('.message-input').boundingBox();
    assert.ok(composer.y + composer.height <= 844 - 72, 'Composer stays above bottom navigation');
    await mobile.getByRole('button', { name: 'Finance', exact: true }).click();
    await mobile.getByRole('heading', { name: 'How should this invoice be paid?' }).waitFor();
    await mobile.evaluate(() => document.fonts.ready);
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    if (capture) await mobile.screenshot({ path: '.impeccable/review/mobile.png', fullPage: true });
    await mobile.getByRole('radio', { name: /USDC route/ }).click();
    await mobile.getByLabel('Who covers downstream fees?').selectOption('buyer');
    assert.match(await mobile.getByRole('radio', { name: /USDC route/ }).innerText(), /9,164\.12/);
    await mobile.locator('.cost-breakdown summary').click();
    assert.match(await mobile.locator('.breakdown-rows').innerText(), /54\.54/);
    assert.match(await mobile.locator('.breakdown-rows').innerText(), /90\.00/);
    assert.match(await mobile.locator('.breakdown-rows').innerText(), /0\.34/);
    await mobile.getByRole('button', { name: 'See the full USDC path' }).click();
    await mobile.getByRole('heading', { name: 'USDC changes the route. Not the FX.' }).waitFor();
    await mobile.getByRole('button', { name: 'Close dialog' }).click();
    await mobile.getByRole('button', { name: 'Chat', exact: true }).click();
    assert.equal(await mobile.locator('.decision-sheet').count(), 0);
    await mobile.getByRole('button', { name: 'Finance', exact: true }).click();
    assert.equal(await mobile.getByRole('radio', { name: /USDC route/ }).getAttribute('aria-checked'), 'true');
    await mobile.goBack();
    await mobile.getByRole('heading', { name: 'Amira Ben Youssef' }).waitFor();
    await mobile.goForward();
    await mobile.getByRole('heading', { name: 'How should this invoice be paid?' }).waitFor();
    await mobile.getByLabel('Who covers downstream fees?').selectOption('buyer');
    await mobile.getByRole('button', { name: 'Review agreement', exact: true }).click();
    await mobile.getByRole('checkbox').check();
    await mobile.getByRole('button', { name: 'Sign as Bilal', exact: true }).click();
    await mobile.getByRole('button', { name: 'Review as Amira' }).click();
    await mobile.getByRole('checkbox').check();
    await mobile.getByRole('button', { name: 'Sign as Amira', exact: true }).click();
    await mobile.getByRole('heading', { name: 'Agreed. And worth keeping.' }).waitFor();
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await mobile.evaluate(() => window.scrollTo(0, 0));
    if (capture) await mobile.screenshot({ path: '.impeccable/review/mobile-sealed.png', fullPage: true });
    const usdcDownloadPromise = mobile.waitForEvent('download');
    await mobile.getByRole('button', { name: 'Download signed record', exact: true }).click();
    const usdcDownload = await usdcDownloadPromise;
    const usdcPath = path.resolve('test-results/mobile-usdc.sanad.json');
    await usdcDownload.saveAs(usdcPath);
    const usdcRecord = JSON.parse(await fs.readFile(usdcPath, 'utf8'));
    assert.equal(usdcRecord.snapshot.quote.id, 'usdc-route');
    assert.equal(usdcRecord.snapshot.costs.totalMaxCad, 9164.12);
    await mobile.getByRole('button', { name: 'Verify or test a change' }).click();
    await mobile.getByLabel('Upload signed record').setInputFiles(usdcPath);
    await mobile.getByRole('heading', { name: 'Record intact. Both signatures valid.' }).waitFor();
    await mobile.getByRole('button', { name: 'Close dialog' }).click();
    await mobile.setViewportSize({ width: 320, height: 740 });
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await mobile.getByRole('button', { name: 'Chat', exact: true }).click();
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await mobile.setViewportSize({ width: 844, height: 390 });
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.deepEqual(errors, []);
    assert.deepEqual(externalRequests, []);
    const result = { status: 'passed', checked: ['quote comparison', 'fee responsibility', 'FX scenario', 'chat', 'consent gating', 'two-tab signing and sync', 'same-tab signing', 'download/import', 'tamper detection', 'original unchanged', 'revision invalidation', 'editable invoice', 'invalid input', 'reset', 'mobile signing', 'no horizontal overflow', 'no uncaught errors', 'no third-party runtime requests', 'separate Chat and Finance screens', 'browser back navigation', 'USDC full-cost decomposition', 'USDC signed export/import', '320px and landscape layouts'], desktop: '1440×1100', mobile: '390×844', errors, externalRequests };
    await fs.writeFile('test-results/browser-check.json', JSON.stringify(result, null, 2));
    console.log(JSON.stringify(result, null, 2));
  } catch (error) { if (capture) await page.screenshot({ path: 'test-results/failure.png', fullPage: true }); throw error; }
  finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
